org.pminin.bot:

  collector:
    collectInterval: 10000
    cutInterval: 600000

  strategies:
  - name: OneMinuteLong
    enabled: true
    description: One Minute Scalper Long
    trigger:
    - previousCandle.close < previousBollinger.lower
    - previousCandle.close - currentPrice > 1.5 * pip
    - recentOrderTime < previousCandle.time
    direction: long
    granularity: M1
    takeProfit: currentPrice + 0.05 * bollinger.width
    stopLoss: currentPrice - 0.5 * bollinger.width
    tradeAmount: 0.2 * nav
    maPeriod: 20
    shift: 1
  - name: OneMinuteShort
    enabled: true
    description: One Minute Scalper Short
    trigger:
    - previousCandle.close > previousBollinger.upper
    - previousCandle.close - currentPrice > 1.5 * pip
    - recentOrderTime < previousCandle.time
    direction: short
    granularity: M1
    takeProfit: currentPrice + 0.05 * bollinger.width
    stopLoss: currentPrice - 0.5 * bollinger.width
    tradeAmount: 0.2 * nav
    maPeriod: 20
    shift: 1

logging.path: ./logs
logging:
  level:
    org.springframework.web: ERROR
    org.pminin.oanda.bot: INFO

#  account:
#    name: pm665
#    accountId: "holder"
#    url: "https://api-fxpractice.oanda.com/"
#    token: "holder"
#
#
#  traderOptions:
#  - accountId: "holder"
#    traders:
#      USD_CAD: [OneMinuteLong, OneMinuteShort]
#      EUR_JPY: [OneMinuteLong, OneMinuteShort]
#  - accountId: "holder"
#    traders:
#      EUR_GBP: [OneMinuteLong, OneMinuteShort]
#      USD_CHF: [OneMinuteLong, OneMinuteShort]

# The following properties are for trading system:
#main:
#  autostart: true
#  scheduler:
#    candle-collect.cron: 0/2 * * * * *
#    start-work.cron: 0 0 1 ? * MON
#    end-work.cron: 0 55 0 ? * SAT
#    forced-work.cron: 0 * 1-23 ? * MON-FRI
#    end-week.cron: 0 55 0 ? * SAT
#    news-check.cron: 0 45 * ? * MON-FRI

